[package]
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
]
description = "Implementation of the BLS12-381 pairing-friendly elliptic curve construction"
documentation = "https://docs.rs/bls12_381/"
homepage = "https://github.com/zkcrypto/bls12_381"
license = "MIT/Apache-2.0"
name = "bls12_381"
repository = "https://github.com/zkcrypto/bls12_381"
version = "0.8.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
digest = {version = "0.9", optional = true }
ff = { version = "0.13", default-features = false }
group = { version = "0.13", default-features = false, optional = true }
pairing = { version = "0.23", optional = true }
rand_core = { version = "0.6", default-features = false }
subtle = { version = "2.2.1", default-features = false }
zeroize = { version = "1.4", default-features = false, optional = true }
sp-crypto-ec-utils = { git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration", version = "0.4.0", default-features = false }
ark-scale = { version = "0.0.3", features = ["hazmat"], default-features = false }
ark-serialize = { version = "0.4.2", default-features = false }
ark-ff = { version = "0.4.2", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
ark-ec = { version = "0.4.2", default-features = false }
ark-bls12-381 = { version = "0.4.0",features = [ "curve" ], default-features = false }
ark-std = { version = "0.4.0", default-features = false }
num-bigint = { version = "0.4", default-features = false }
blst = { version = "0.3.10" }
byte-slice-cast = "1.2.2"

[dev-dependencies]
csv = ">= 1.0, < 1.2" # csv 1.2 has MSRV 1.60
criterion = "0.3"
hex = "0.4"
rand_xorshift = "0.3"
sha2 = "0.9"
sha3 = "0.9"

[[bench]]
name = "groups"
harness = false
required-features = ["groups"]

[[bench]]
name = "hash_to_curve"
harness = false
required-features = ["experimental"]

[features]
default = ["groups", "pairings", "alloc", "bits"]
std = [
    "sp-crypto-ec-utils/std",
]
bits = ["ff/bits"]
groups = ["group"]
pairings = ["groups", "pairing", "std"]
alloc = ["group/alloc"]
experimental = ["digest"]
nightly = ["subtle/nightly"]
